// Generated by Tools/ui_text.py through generate_content.py. Do not edit.
public static class GeneratedUiText
{
    public static string Get(int id, int language)
    {
        switch (id)
        {
            case 133: return new[] { "Expected damage", "예상 피해", "Expected damage", "予想ダメージ", "预计伤害" }[language >= 0 && language <= 4 ? language : 0];
            case 134: return new[] { "You will fall", "쓰러진다", "You will fall", "倒れます", "将会倒下" }[language >= 0 && language <= 4 ? language : 0];
            case 135: return new[] { "Cannot win", "못 이긴다", "Cannot win", "勝てません", "无法获胜" }[language >= 0 && language <= 4 ? language : 0];
            case 140: return new[] { "Start game", "게임 시작", "Start game", "ゲーム開始", "开始游戏" }[language >= 0 && language <= 4 ? language : 0];
            case 141: return new[] { "New game", "새 게임", "New game", "ニューゲーム", "新游戏" }[language >= 0 && language <= 4 ? language : 0];
            case 142: return new[] { "Continue", "이어하기", "Continue", "つづきから", "继续游戏" }[language >= 0 && language <= 4 ? language : 0];
            case 143: return new[] { "Press any key", "아무 키나 누르세요", "Press any key", "何かキーを押してください", "请按任意键" }[language >= 0 && language <= 4 ? language : 0];
            case 144: return new[] { "Loading failed. Enter: retry / Esc: quit", "불러오지 못했습니다. Enter: 재시도 / Esc: 종료", "Loading failed. Enter: retry / Esc: quit", "読み込めませんでした。Enter：再試行 / Esc：終了", "加载失败。Enter：重试 / Esc：退出" }[language >= 0 && language <= 4 ? language : 0];
            case 145: return new[] { "Could not restore your save. The original is preserved. Press any key to return.", "저장을 복구하지 못했습니다. 원본은 보존됩니다. 아무 키나 눌러 돌아가세요.", "Could not restore your save. The original is preserved. Press any key to return.", "セーブを復元できませんでした。元のデータは保持されます。何かキーを押して戻ります。", "无法恢复存档。原始存档已保留。请按任意键返回。" }[language >= 0 && language <= 4 ? language : 0];
            case 146: return new[] { "Taking one reward removes the other.", "둘 중 하나를 얻으면 다른 보상은 사라집니다.", "Taking one reward removes the other.", "片方を取ると、もう片方の報酬は消えます。", "领取一个奖励后，另一个奖励将消失。" }[language >= 0 && language <= 4 ? language : 0];
            default: return null;
        }
    }
}
