"""손으로 쓴 ScriptData 행의 네 언어 — 메뉴·능력치·소모품·장비·1~4층·도입부 몬스터.

값은 ScriptData 칸에 들어가는 그대로다: 줄바꿈은 글자 그대로의 \\n, 쉼표는 ^ 로 적는다.
GetString 이 둘 다 되돌리고, 어드레서블 전 GeneratedUiText 로 나가도 같은 길을 탄다.
이 행들은 이제 여기가 원본이다 — ScriptData.json 을 손으로 고치면 generate_content --write 가 되돌린다.

영어는 CSV 에서 쉼표로 잘려 일본어·중국어 칸으로 샌 10행(126 4009 4017 4033 4039 20000
20004 20005 20007 20008)을 한국어 뜻으로 다시 잇고, 백틱(`)을 ' 로, 없는 스탯인 stamina 를
HP 로, 뜻이 틀린 18(Full Volume)·4020(Ballet Font)·128 을 고쳤다. 한국어는 4057 의 문장 가운데
마침표 하나만 고쳤다.
아무 표도 가리키지 않는 옛 행(1~5, 5004~5099, 101xx·103xx, 201xx·203xx)은 넣지 않았다.
워프석 반지(4000·4001)는 여기 없다 — 스토리 도감 items.warp_ring 이 원본이다(도감 4060·4061 과 같은 길).
"""

TEXT = {
    # 메뉴·설정 (Define.CONTINUE ~ EFFECT)
    9: ("계속하기", "Continue", "続ける", "继续"),
    10: ("설정", "Settings", "設定", "设置"),
    11: ("언어", "Language", "言語", "语言"),
    12: ("게임 종료", "Exit Game", "ゲーム終了", "退出游戏"),
    13: ("화면", "Screen", "画面", "显示"),
    14: ("전체 화면", "Full Screen", "フルスクリーン", "全屏"),
    15: ("창 모드", "Window Mode", "ウィンドウ", "窗口模式"),
    16: ("전체 창 모드", "Full Window Mode", "ボーダーレス", "无边框窗口"),
    17: ("소리", "Sound", "サウンド", "声音"),
    18: ("전체 음량", "Master Volume", "全体音量", "主音量"),
    19: ("배경음", "Background Sound", "BGM", "音乐"),
    20: ("효과음", "Sound Effects", "効果音", "音效"),
    # 처음 한 번 뜨는 안내 (Define.GUIDE_*, UI_GuidePopup)
    21: ("몬스터에 부딪치면 전투가 시작됩니다!",
         "When you hit a monster^ the battle begins!",
         "モンスターにぶつかると戦闘が始まります！",
         "碰到怪物就会开始战斗！"),
    22: ("음식과 물약을 획득하면 체력이 회복 됩니다!",
         "Get food and potions to restore your health!",
         "食べ物やポーションを手に入れると体力が回復します！",
         "获得食物和药水就能恢复生命值！"),
    23: ("열쇠와 같은 색깔의 문을 열 수 있습니다!",
         "You can open doors of the same color as the key!",
         "鍵と同じ色の扉を開けられます！",
         "可以打开与钥匙同色的门！"),
    24: ("특정 기믹을 해제하여 나아가세요!",
         "Unlock certain gimmicks to advance!",
         "仕掛けを解いて先へ進みましょう！",
         "解开机关，继续前进吧！"),
    # 능력치 이름 (UI_InvenPopup, STAT_INFO_SCRIPT + i). 102 는 전투 예측의 "체력" 이기도 하다
    100: ("공격력", "Attack Power", "攻撃力", "攻击力"),
    101: ("방어력", "Defense Power", "防御力", "防御力"),
    102: ("체력", "Health", "体力", "生命值"),
    103: ("치명 확률", "Critical Chance", "会心率", "暴击率"),
    104: ("치명 공격력", "Critical Attack Power", "会心ダメージ", "暴击伤害"),
    105: ("레벨", "Level", "レベル", "等级"),
    106: ("공격 속도", "Attack Speed", "攻撃速度", "攻击速度"),
    107: ("방어 속도", "Defense Speed", "防御速度", "防御速度"),
    108: ("이동 속도", "Movement Speed", "移動速度", "移动速度"),
    # 소모품 이름 109~120 · 설명 121~132 (ConsumableItemData)
    109: ("초록 열쇠", "Green Key", "緑の鍵", "绿钥匙"),
    110: ("노랑 열쇠", "Yellow Key", "黄色の鍵", "黄钥匙"),
    111: ("붉은 열쇠", "Red Key", "赤い鍵", "红钥匙"),
    112: ("사과", "Apple", "リンゴ", "苹果"),
    113: ("고기", "Meat", "肉", "肉块"),
    114: ("소형 물약", "Small Potion", "小ポーション", "小型药水"),
    115: ("중형 물약", "Medium Potion", "中ポーション", "中型药水"),
    116: ("대형 물약", "Large Potion", "大ポーション", "大型药水"),
    117: ("축복 물약", "Blessing Potion", "祝福のポーション", "祝福药水"),
    118: ("공격 룬", "Attack Rune", "攻撃のルーン", "攻击符文"),
    119: ("방어 룬", "Defense Rune", "防御のルーン", "防御符文"),
    120: ("체력 룬", "Health Rune", "体力のルーン", "生命符文"),
    121: ("초록 빛이 감도는 청동 열쇠.\\n닫힌 초록색 문에 사용할 수 있을 것 같다.",
          "A bronze key with a green glow.\\nIt seems like it could be used on closed green doors.",
          "緑の光を帯びた青銅の鍵。\\n閉ざされた緑の扉に使えそうだ。",
          "泛着绿光的青铜钥匙。\\n似乎能打开紧闭的绿色门。"),
    122: ("노랑 빛이 감도는 황동 열쇠.\\n닫힌 노랑색 문에 사용할 수 있을 것 같다.",
          "A brass key with a yellow glow.\\nIt seems like it could be used on closed yellow doors.",
          "黄色い光を帯びた真鍮の鍵。\\n閉ざされた黄色の扉に使えそうだ。",
          "泛着黄光的黄铜钥匙。\\n似乎能打开紧闭的黄色门。"),
    123: ("붉은 빛이 감도는 구리 열쇠.\\n닫힌 붉은색 문에 사용할 수 있을 것 같다.",
          "A copper key with a red glow.\\nIt seems like it could be used on closed red doors.",
          "赤い光を帯びた銅の鍵。\\n閉ざされた赤い扉に使えそうだ。",
          "泛着红光的铜钥匙。\\n似乎能打开紧闭的红色门。"),
    124: ("빨갛게 잘 익은 사과.\\n약간의 허기를 채워주어\\n기운을 북돋아 주는 것 같다.\\n체력회복 <color=#00FF7F><b>+20%</b></color>",
          "A ripe red apple.\\nIt seems to fill a little hunger\\nand boost energy.\\nRestores HP <color=#00FF7F><b>+20%</b></color>",
          "赤くよく熟れたリンゴ。\\n少し空腹を満たして\\n元気づけてくれそうだ。\\n体力回復 <color=#00FF7F><b>+20%</b></color>",
          "红透了的熟苹果。\\n能稍微填一填肚子\\n让人打起些精神。\\n生命值恢复 <color=#00FF7F><b>+20%</b></color>"),
    125: ("두툼한 고기 조각.\\n배고픔에 지친 모험가에게\\n힘이 나게 해준다.\\n체력회복 <color=#00FF7F><b>+30%</b></color>",
          "A thick piece of meat.\\nIt gives strength to adventurers\\nwho are exhausted from hunger.\\nRestores HP <color=#00FF7F><b>+30%</b></color>",
          "分厚い肉の塊。\\n空腹で疲れ果てた冒険者に\\n力を与えてくれる。\\n体力回復 <color=#00FF7F><b>+30%</b></color>",
          "厚实的肉块。\\n能让饿得筋疲力尽的冒险者\\n重新充满力气。\\n生命值恢复 <color=#00FF7F><b>+30%</b></color>"),
    126: ("작은 병에 담긴 물약.\\n흔한 약초를 달여 만들었지만\\n빠르게 체력을 회복시켜준다..\\n체력회복 <color=#00FF7F><b>+40%</b></color>",
          "A potion in a small bottle.\\nIt is made by boiling common herbs^\\nbut it quickly restores health..\\nRestores HP <color=#00FF7F><b>+40%</b></color>",
          "小瓶に入ったポーション。\\nありふれた薬草を煎じたものだが\\nすばやく体力を回復してくれる。\\n体力回復 <color=#00FF7F><b>+40%</b></color>",
          "装在小瓶里的药水。\\n虽然只是用常见草药熬成的\\n却能迅速恢复生命值。\\n生命值恢复 <color=#00FF7F><b>+40%</b></color>"),
    127: ("넉넉한 병에 담긴 물약.\\n비싼 약초가 사용되어 비싸게 거래된다.\\n지친 모험가도 즉시 회복시켜줄 수 있다..\\n체력회복 <color=#00FF7F><b>+50%</b></color>",
          "A potion in a generous bottle.\\nIt is traded at a high price because it uses expensive herbs.\\nIt can instantly restore even exhausted adventurers..\\nRestores HP <color=#00FF7F><b>+50%</b></color>",
          "大きめの瓶に入ったポーション。\\n高価な薬草を使うため高値で取引される。\\n疲れ果てた冒険者もたちまち回復させる。\\n体力回復 <color=#00FF7F><b>+50%</b></color>",
          "装在大瓶里的药水。\\n用了名贵的草药，因此售价不菲。\\n能让精疲力竭的冒险者立刻恢复。\\n生命值恢复 <color=#00FF7F><b>+50%</b></color>"),
    # +70% 였다 — ConsumableItemData 7 의 Heal 은 60 이다 (4층 분열 슬라임이 떨군다).
    128: ("귀한 약초로 약사가 특별하게 제조하여\\n실신한 사람도 벌떡 일어나게 만든다..\\n체력회복 <color=#00FF7F><b>+60%</b></color>",
          "Specially brewed by an apothecary from rare herbs^\\nit gets even the fainted back on their feet..\\nRestores HP <color=#00FF7F><b>+60%</b></color>",
          "薬師が貴重な薬草で特別に調合したもの。\\n気を失った者さえ飛び起きるという。\\n体力回復 <color=#00FF7F><b>+60%</b></color>",
          "药师用珍贵草药特别调制而成，\\n连昏倒的人都能一下子跳起来。\\n生命值恢复 <color=#00FF7F><b>+60%</b></color>"),
    129: ("신비로운 빛이 나는 물약.\\n죽은 사람도 살린다는 기적의 물약으로\\n제조법을 찾기 위한 약사들이 앞다퉈 연구 중이다..\\n체력회복 <color=#00FF7F><b>+100%</b></color>",
          "A potion with a mysterious glow.\\nIt is a miraculous potion that can even revive the dead.\\nPharmacists are racing to find the recipe..\\nRestores HP <color=#00FF7F><b>+100%</b></color>",
          "神秘的な光を放つポーション。\\n死者さえ蘇らせるという奇跡の薬で\\n薬師たちが競って製法を研究している。\\n体力回復 <color=#00FF7F><b>+100%</b></color>",
          "散发着神秘光芒的药水。\\n传说是能起死回生的奇迹之药\\n药师们正争相研究它的配方。\\n生命值恢复 <color=#00FF7F><b>+100%</b></color>"),
    130: ("파괴의 힘이 담긴 마석.\\n마법으로 새겨진 고대 문자가 빛나고 있다.\\n내면에서 파괴의 힘이 솟아난다.",
          "A magic stone with the power of destruction.\\nAncient letters engraved with magic are shining.\\nThe power of destruction rises from within.",
          "破壊の力を宿した魔石。\\n魔法で刻まれた古代文字が輝いている。\\n内から破壊の力が湧き上がる。",
          "蕴含破坏之力的魔石。\\n以魔法刻下的古代文字闪闪发光。\\n破坏之力自体内涌出。"),
    131: ("인내의 힘이 담긴 마석.\\n마법으로 새겨진 고대 문자가 빛나고 있다.\\n내면에서 인내의 힘이 솟아난다.",
          "A magic stone with the power of endurance.\\nAncient letters engraved with magic are shining.\\nThe power of endurance rises from within.",
          "忍耐の力を宿した魔石。\\n魔法で刻まれた古代文字が輝いている。\\n内から忍耐の力が湧き上がる。",
          "蕴含忍耐之力的魔石。\\n以魔法刻下的古代文字闪闪发光。\\n忍耐之力自体内涌出。"),
    132: ("생명의 힘이 담긴 마석.\\n마법으로 새겨진 고대 문자가 빛나고 있다.\\n내면에서 생명의 힘이 솟아난다.",
          "A magic stone with the power of life.\\nAncient letters engraved with magic are shining.\\nThe power of life rises from within.",
          "生命の力を宿した魔石。\\n魔法で刻まれた古代文字が輝いている。\\n内から生命の力が湧き上がる。",
          "蕴含生命之力的魔石。\\n以魔法刻下的古代文字闪闪发光。\\n生命之力自体内涌出。"),
    # 장비 이름·설명 (EquipData NameId/DescId). 4000·4001 반지와 4060·4061 도감은 스토리 도감,
    # 4018·4029 에고소드는 story_gen 몫
    4002: ("레인저 부츠", "Ranger Boots", "レンジャーブーツ", "游侠之靴"),
    4003: ("스피리트 윈드 부츠", "Spirit Wind Boots", "風霊のブーツ", "风灵之靴"),
    4004: ("엔젤 윙 부츠", "Angel Wing Boots", "天使の翼のブーツ", "天使之翼靴"),
    4005: ("타르타로스 부츠", "Tartaros Boots", "タルタロスブーツ", "塔尔塔罗斯之靴"),
    4006: ("활동성이 보장된 부츠.\\n가벼운 발걸음을 선사하여 이동 속도를 증가시켜준다.",
           "Boots with guaranteed mobility.\\nIt increases movement speed by giving you a light step.",
           "動きやすさ抜群のブーツ。\\n足取りを軽くし、移動速度を上げてくれる。",
           "行动灵活自如的靴子。\\n让脚步变得轻盈，提升移动速度。"),
    4007: ("바람의 정령이 깃든 부츠.\\n바람의 마법으로 매우 가볍게 이동할 수 있다.",
           "Boots imbued with the spirit of the wind.\\nYou can move very lightly with the magic of the wind.",
           "風の精霊が宿るブーツ。\\n風の魔法でとても軽やかに移動できる。",
           "附有风之精灵的靴子。\\n借助风之魔法，可以极其轻盈地移动。"),
    4008: ("천사의 날개가 달린 부츠.\\n고귀한 천사의 날개가 원하는 곳으로 인도한다.",
           "Boots with angel wings.\\nThe wings of a noble angel will lead you to where you want to go.",
           "天使の翼がついたブーツ。\\n気高き天使の翼が望む場所へと導いてくれる。",
           "装有天使之翼的靴子。\\n高贵的天使之翼会引领你去往想去的地方。"),
    4009: ("심연의 명계 타르타로스의 부츠.\\n걷지 않아도 알아서 움직이며^ 그 속도는 차원을 달리한다.",
           "Boots of Tartarus^ the abyssal underworld.\\nThey carry you without a single step^ at a speed from another dimension.",
           "深淵の冥界タルタロスのブーツ。\\n歩かずとも勝手に動き、その速さは次元が違う。",
           "深渊冥界塔尔塔罗斯的靴子。\\n无需迈步便会自行移动，其速度已是另一个次元。"),
    4010: ("모래시계 목걸이", "Sandglass Necklace", "砂時計の首飾り", "沙漏项链"),
    4011: ("에온의 고리", "Aeon's Ring", "アイオーンの輪", "埃昂之环"),
    4012: ("키르케의 시계추", "Circe's Pendulum", "キルケーの振り子", "喀耳刻的钟摆"),
    4013: ("크로노스의 시계", "Chronos's Clock", "クロノスの時計", "克洛诺斯之钟"),
    4014: ("마법의 모래시계로 만든 목걸이.\\n시간의 흐름을 이용하여 전투 시간을 앞당긴다.",
           "A necklace made from a magic hourglass.\\nUtilizes the flow of time to advance battle time.",
           "魔法の砂時計で作った首飾り。\\n時の流れを利用して戦闘の時間を早める。",
           "用魔法沙漏制成的项链。\\n利用时间的流动，加快战斗进程。"),
    4015: ("시간 여행자인 에온의 고리로 만든 목걸이.\\n시간의 흐름을 제어하여 전투 시간을 신속하게 앞당긴다.",
           "A necklace made from the ring of the time traveler Aeon.\\nControls the flow of time to quickly advance battle time.",
           "時の旅人アイオーンの輪で作った首飾り。\\n時の流れを制御し、戦闘の時間を素早く進める。",
           "用时间旅者埃昂之环制成的项链。\\n掌控时间的流动，迅速加快战斗进程。"),
    4016: ("마녀 키르케의 시계추로 만든 목걸이.\\n시간의 흐름을 변형시켜 전투시간을 빠르게 앞당긴다.",
           "A necklace made from the pendulum of the witch Circe.\\nDistorts the flow of time to quickly advance battle time.",
           "魔女キルケーの振り子で作った首飾り。\\n時の流れを歪め、戦闘の時間を速く進める。",
           "用魔女喀耳刻的钟摆制成的项链。\\n扭曲时间的流动，大幅加快战斗进程。"),
    4017: ("시간의 신 크로노스의 시계로 만든 목걸이.\\n시간의 흐름을 재구축하여 전투시간을 급격하게 앞당긴다.",
           "A necklace made from the clock of Chronos^ the god of time.\\nReconstructs the flow of time to rapidly advance battle time.",
           "時の神クロノスの時計で作った首飾り。\\n時の流れを再構築し、戦闘の時間を一気に進める。",
           "用时间之神克洛诺斯之钟制成的项链。\\n重构时间的流动，急剧加快战斗进程。"),
    4019: ("애페스티온", "Aphestion", "アフェスティオン", "阿菲斯提昂"),
    4020: ("발레폰트", "Valefont", "ヴァレフォント", "瓦勒丰特"),
    4021: ("루나리스", "Lunaris", "ルナリス", "卢娜里斯"),
    4022: ("드라코닉스", "Draconix", "ドラコニクス", "德拉科尼克斯"),
    # 4022 와 같은 "드라코닉스" 였다 — EquipData 15 는 아르칸디스(마법의 검, 4034)다.
    4023: ("아르칸디스", "Arcandis", "アルカンディス", "阿尔坎迪斯"),
    4024: ("엑스칼리버", "Excalibur", "エクスカリバー", "王者之剑"),
    4025: ("피닉시아", "Phoenixia", "フェニキシア", "菲尼克西亚"),
    4026: ("라이타니온", "Raitanion", "ライタニオン", "雷塔尼昂"),
    4027: ("움브라노크스", "Umbranox", "ウンブラノクス", "安布拉诺克斯"),
    4028: ("라그나브레이크", "Ragnar Break", "ラグナブレイク", "拉格纳布雷克"),
    4030: ("기도의 검\\n신성한 임무를 수행하기 위해 고대 사제가 제작한 검으로^\\n사용자에게 기본적인 보호와 축복을 내린다.",
           "Sword of Prayer\\nA sword made by an ancient priest to perform a sacred mission^\\nit grants the user basic protection and blessings.",
           "祈りの剣\\n神聖な使命を果たすため古代の司祭が作った剣で、\\n使い手に基本的な加護と祝福を授ける。",
           "祈祷之剑\\n古代祭司为完成神圣使命而打造的剑，\\n能赐予使用者基本的守护与祝福。"),
    4031: ("영웅의 검\\n100년 전^ 마을을 괴롭히던 괴물을 무찌르고\\n그 영웅의 이름을 따서 불리게 되었다.",
           "Sword of the Hero\\n100 years ago^ it slew the monster plaguing the village\\nand came to be named after that hero.",
           "英雄の剣\\n100年前、村を苦しめていた怪物を討ち倒し\\nその英雄の名で呼ばれるようになった。",
           "英雄之剑\\n百年前曾讨伐为祸村庄的怪物\\n从此便以那位英雄之名相称。"),
    4032: ("달의 검\\n달의 여신이 마물을 물리치기 위해^\\n달빛이 깃든 은으로 만든 성스러운 검이다.",
           "Sword of the Moon\\nA sacred sword made of silver imbued with moonlight by the goddess of the moon to defeat the monsters.",
           "月の剣\\n月の女神が魔物を退けるため、\\n月光を宿した銀で作った聖なる剣。",
           "月之剑\\n月之女神为击退魔物，\\n用蕴含月光的白银打造的圣剑。"),
    4033: ("용의 검\\n고대의 용의 이빨로 만들어져^ 용의 불꽃을\\n내뿜을 수 있는 전설적인 용 사냥꾼의 무기이다.",
           "Dragon Sword\\nMade from the teeth of an ancient dragon^ it breathes dragon fire\\nand was the weapon of a legendary dragon hunter.",
           "竜の剣\\n古代竜の牙から作られ、竜の炎を\\n吐き出せる伝説の竜狩りの武器。",
           "龙之剑\\n以远古巨龙的牙齿打造，能喷吐龙焰\\n是传说中屠龙猎人的武器。"),
    4034: ("마법의 검\\n정체불명의 마법이 깃든 보석이 박혀 있어^\\n사용자의 능력을 증폭시키는 강력한 마법 검이다.",
           "Magic Sword\\nA powerful magical sword with a jewel imbued with an unknown magic\\nthat amplifies the user's abilities.",
           "魔法の剣\\n正体不明の魔法を宿した宝石がはめ込まれ、\\n使い手の力を増幅させる強力な魔法剣。",
           "魔法之剑\\n镶嵌着蕴含不明魔法的宝石，\\n是能增幅使用者能力的强大魔法剑。"),
    4035: ("빛의 검\\n빛의 수호자에 의해 만들어져 어둠의 존재들을\\n물리치고 정의를 수호하는 힘을 지녔다.",
           "Light Sword\\nMade by the Guardian of Light^ it has the power to defeat dark beings\\nand protect justice.",
           "光の剣\\n光の守護者によって作られ、闇の存在を\\n退け正義を守る力を持つ。",
           "光之剑\\n由光之守护者打造，拥有击退黑暗存在、\\n守护正义的力量。"),
    4036: ("부활의 검\\n불사조의 깃털로 만들어져^ 사용자가 쓰러져도\\n불꽃 속에서 다시 일어날 수 있는 부활의 힘을 지닌다.",
           "Resurrection Sword\\nMade from the feathers of the phoenix^ it has the power of resurrection that allows the user to rise again in flames even if they fall.",
           "復活の剣\\n不死鳥の羽根から作られ、使い手が倒れても\\n炎の中から再び立ち上がれる復活の力を持つ。",
           "复活之剑\\n以不死鸟的羽毛打造，即使使用者倒下\\n也能凭复活之力从火焰中再度站起。"),
    4037: ("천둥의 검\\n천둥신이 내린 벼락으로 단련한 검으로^\\n적에게 치명적인 번개의 힘을 가할 수 있다.",
           "Thunder Sword\\nA sword forged from the thunderbolts of the god of thunder^ it can inflict deadly lightning power on enemies.",
           "雷の剣\\n雷神が落とした稲妻で鍛えた剣で、\\n敵に致命的な雷の力を叩き込める。",
           "雷霆之剑\\n以雷神降下的霹雳锻造而成，\\n能对敌人施加致命的雷电之力。"),
    4038: ("저주의 검\\n어둠의 심연에서 나온 재료로 만들어져^\\n적의 생명력을 흡수하여 사용자를 치유하는 능력을 지녔다.",
           "Curse Sword\\nMade from materials from the abyss of darkness^ it has the ability to absorb the life force of enemies and heal the user.",
           "呪いの剣\\n闇の深淵から生まれた素材で作られ、\\n敵の生命力を吸い取って使い手を癒やす力を持つ。",
           "诅咒之剑\\n以来自黑暗深渊的材料打造，\\n能吸取敌人的生命力来治愈使用者。"),
    4039: ("절대자의 검\\n신들의 전쟁에서 사용된 전설의 검으로^ 그 힘은\\n세계를 재구성할 수 있을 정도로 강력하며 다양한 능력을 가지고 있다.",
           "Absolute Sword\\nA legendary sword used in the war of the gods^ its power\\nis great enough to reshape the world^ and it holds many abilities.",
           "絶対者の剣\\n神々の戦争で使われた伝説の剣で、その力は\\n世界を作り変えるほど強大で、多彩な能力を秘めている。",
           "绝对者之剑\\n诸神之战中使用过的传说之剑，其力量\\n强大到足以重塑世界，并拥有多种能力。"),
    4040: ("헌터 실드", "Hunter Shield", "ハンターの盾", "猎人之盾"),
    4041: ("오크나이트 실드", "Orc Knight Shield", "オークナイトの盾", "兽人骑士之盾"),
    # 중국어 "铁壁" 는 스킬 철벽(强击·铁壁·吸血)과 같은 말이라 방패가 그 스킬로 읽힌다
    4042: ("아이언 월", "Iron Wall", "アイアンウォール", "铁墙之盾"),
    4043: ("에메랄드 실드", "Emerald Shield", "エメラルドの盾", "翡翠之盾"),
    4044: ("미스릴 실드", "Mithril Shield", "ミスリルの盾", "秘银之盾"),
    4045: ("그리폰 실드", "Griffon Shield", "グリフォンの盾", "狮鹫之盾"),
    4046: ("가디언 실드", "Guardian Shield", "ガーディアンの盾", "守护者之盾"),
    4047: ("트리톤 실드", "Triton Shield", "トリトンの盾", "特里同之盾"),
    4048: ("쉐도우 실드", "Shadow Shield", "影の盾", "暗影之盾"),
    4049: ("엘드리치 실드", "Eldritch Shield", "エルドリッチの盾", "埃尔德里奇之盾"),
    4050: ("야수를 사냥하는 헌터들이 주로 사용하던 방패.\\n작고 가벼워 적의 간단한 공격은 막을 수 있다.",
           "A shield mainly used by hunters who hunt wild beasts.\\nIt is small and light^ so it can block simple attacks from enemies.",
           "獣を狩るハンターたちが主に使っていた盾。\\n小さく軽いが、敵の単純な攻撃なら防げる。",
           "猎人们狩猎野兽时常用的盾牌。\\n小巧轻便，能挡住敌人的简单攻击。"),
    4051: ("오크 전사가 사용하던 방패.\\n만듦새는 투박하지만 방어 능력은 보장한다.",
           "A shield used by orc warriors.\\nIt is made roughly^ but its defensive capabilities are guaranteed.",
           "オークの戦士が使っていた盾。\\n作りは粗いが、守りの力は確かだ。",
           "兽人战士使用过的盾牌。\\n做工虽粗糙，防御能力却有保障。"),
    4052: ("거대한 철의 벽처럼 단단한 방패.\\n어떠한 공격도 막아내며 소유자의 방어력을 극대화한다.",
           "A shield as solid as a giant iron wall.\\nIt blocks any attack and maximizes the owner's defensive capabilities.",
           "巨大な鉄の壁のように頑丈な盾。\\nあらゆる攻撃を防ぎ、持ち主の防御力を最大限に高める。",
           "如巨大铁墙般坚固的盾牌。\\n能挡下任何攻击，将持有者的防御力提升到极致。"),
    4053: ("숲의 정령들의 기운을 머금은 방패.\\n자연의 힘으로 상처를 치유하고 보호하는 효과가 있다.",
           "A shield imbued with the energy of forest spirits.\\nIt has the effect of healing and protecting wounds with the power of nature.",
           "森の精霊たちの気を宿した盾。\\n自然の力で傷を癒やし、身を守る効果がある。",
           "蕴含森林精灵气息的盾牌。\\n能借自然之力治愈伤口、守护持有者。"),
    4054: ("드워프가 신비한 광석^ 미스릴로 만든 방패.\\n매우 가벼우면서도 뛰어난 방어력을 자랑한다.",
           "A shield made by dwarves from the mysterious ore^ Mithril.\\nIt is very light^ but boasts excellent defensive capabilities.",
           "ドワーフが神秘の鉱石ミスリルで作った盾。\\nとても軽いのに、優れた防御力を誇る。",
           "矮人用神秘矿石秘银打造的盾牌。\\n极为轻巧，却拥有出色的防御力。"),
    4055: ("신성한 그리폰의 날개와 갈퀴로 장식된 방패.\\n하늘과 땅을 아우르는 기동성과 보호력을 가지고 있다.",
           "A shield decorated with the wings and claws of a sacred griffon.\\nIt has mobility and protection that encompasses the sky and the ground.",
           "神聖なグリフォンの翼と鉤爪で飾られた盾。\\n天と地をまたにかける機動力と守りの力を持つ。",
           "以神圣狮鹫的翅膀与利爪装饰的盾牌。\\n兼具纵横天地的机动性与防护力。"),
    4056: ("고대 가디언이 사용했던 방패.\\n주인에 대한 절대적인 수호를 약속한다.",
           "A shield used by ancient guardians.\\nIt promises absolute protection for its owner.",
           "古代のガーディアンが使っていた盾。\\n持ち主に絶対の守護を約束する。",
           "古代守护者使用过的盾牌。\\n向主人许下绝对守护的誓约。"),
    4057: ("바다의 신 트리톤이 사용하던 방패.\\n물과 바다의 힘을 가지고 있으며^ 신의 가호로 보호한다.",
           "A shield used by Triton^ the god of the sea.\\nIt has the power of water and the sea^ and protects with the protection of the god.",
           "海の神トリトンが使っていた盾。\\n水と海の力を宿し、神の加護で守ってくれる。",
           "海神特里同使用过的盾牌。\\n蕴含水与海之力，以神的庇护守护持有者。"),
    4058: ("어둠을 재료로 만들었다는 믿기 힘든 방패.\\n소유자는 그림자 속에서 은밀하게 움직일 수 있다고 전해진다.",
           "An incredible shield made of darkness.\\nIt is said that the owner can move stealthily in the shadows.",
           "闇を素材に作ったという、信じがたい盾。\\n持ち主は影の中を密かに動けると伝えられる。",
           "据说以黑暗为材料打造，令人难以置信的盾牌。\\n相传持有者能在阴影中悄然行动。"),
    4059: ("언데드 마법사 엘드리치의 힘이 깃든 방패.\\n강대한 마력이 휘몰아치고 있어 그에 걸맞은 자가 아니면 사용할 수 없다.",
           "A shield imbued with the power of the undead wizard Eldritch.\\nA powerful magical power swirls around^ so only those who are worthy can use it.",
           "アンデッドの魔法使いエルドリッチの力が宿る盾。\\n強大な魔力が渦巻き、ふさわしい者でなければ扱えない。",
           "蕴含亡灵法师埃尔德里奇之力的盾牌。\\n强大的魔力在其中翻涌，唯有配得上它的人才能使用。"),
    # 손수 만든 1~4층 이름 (StageInfoData). 5층부터는 생성기가 5105~ 에 쓴다
    5000: ("마물의 숲", "Forest of Demons", "魔物の森", "魔物之森"),
    5001: ("마물의 숲 안쪽", "Inside the Forest of Demons", "魔物の森の奥", "魔物之森深处"),
    5002: ("잊혀진 숲", "Forgotten Forest", "忘れられた森", "遗忘之森"),
    5003: ("숲의 유적", "Ruins of the Forest", "森の遺跡", "森林遗迹"),
    # 도입부 몬스터 0~8 — 이름 10000~, 설명 20000~ (MonsterData)
    10000: ("라임 슬라임", "Lime Slime", "ライムスライム", "青柠史莱姆"),
    10001: ("망고 슬라임", "Mango Slime", "マンゴースライム", "芒果史莱姆"),
    10002: ("크로우", "Crow", "クロウ", "乌鸦"),
    10003: ("숲의 정령", "Forest Spirit", "森の精霊", "森林精灵"),
    10004: ("야생 늑대", "Wild Wolf", "野生の狼", "野狼"),
    10005: ("킹 슬라임", "King Slime", "キングスライム", "史莱姆王"),
    10006: ("둔기 슬라임", "Blunt Slime", "鈍器スライム", "钝器史莱姆"),
    10007: ("단검 슬라임", "Dagger Slime", "短剣スライム", "短剑史莱姆"),
    10008: ("방패 슬라임", "Shield Slime", "盾スライム", "盾牌史莱姆"),
    20000: ("밝고 투명한 녹색을 띠는 슬라임.\\n주로 숲 근처에 서식하며^ 상쾌한 라임 향기를 내뿜는다.\\n공격 받을 때마다 주변 공기를 상쾌하게 만들지만^\\n동시에 끈적한 산성 액체를 뿌려 적을 공격한다.",
            "A slime with a bright^ transparent green color.\\nIt mainly lives near forests^ and exudes a refreshing lime scent.\\nWhen attacked^ it refreshes the surrounding air^\\nbut at the same time^ it sprays a sticky^ acidic liquid to attack enemies.",
            "明るく透き通った緑色のスライム。\\n主に森の近くに棲み、さわやかなライムの香りを放つ。\\n攻撃を受けるたびに周りの空気をさわやかにするが、\\n同時にねばつく酸性の液をまき散らして敵を攻撃する。",
            "呈明亮透明绿色的史莱姆。\\n主要栖息在森林附近，散发着清新的青柠香气。\\n每次受到攻击都会让周围的空气变得清新，\\n同时也会喷出黏稠的酸液攻击敌人。"),
    20001: ("노란 망고 향을 풍기는 슬라임.\\n주로 망고 나무 아래에서 발견되며^ 익은 망고를 먹으며 자란다.\\n몸체에서 떨어진 액체는 영양분이 높아^ 주변 식물이 빠르게 자란다.\\n적을 달콤한 향기로 유인한 뒤^ 끈적한 점액으로 공격한다.",
            "A slime that smells like yellow mango.\\nIt is usually found under mango trees^ and grows by eating ripe mangoes.\\nThe liquid that drips from its body is highly nutritious^ and causes nearby plants to grow quickly.\\nIt lures enemies with its sweet scent^ and then attacks them with sticky mucus.",
            "黄色いマンゴーの香りを漂わせるスライム。\\n主にマンゴーの木の下で見つかり、熟したマンゴーを食べて育つ。\\n体から滴る液は栄養たっぷりで、周りの植物がぐんぐん育つ。\\n甘い香りで敵をおびき寄せ、ねばつく粘液で攻撃する。",
            "散发着黄色芒果香气的史莱姆。\\n常在芒果树下出没，以熟透的芒果为食。\\n身上滴落的液体营养丰富，能让周围的植物迅速生长。\\n它会用甜美的香气引诱敌人，再用黏稠的黏液发动攻击。"),
    20002: ("지능이 높고 숲속에 서식하는 변종 까마귀.\\n불길한 징조를 알리는 존재로 여겨지며^ 검은 깃털과 붉은 눈이 특징.\\n어둠 속에서 적의 시야를 차단하고^ 그들의 약점을 찾아내 공격하는 데 능숙하다.",
            "A highly intelligent mutant crow that lives in the forest.\\nConsidered to be a being that announces ominous omens^ it is characterized by its black feathers and red eyes.\\nIt is adept at blocking the vision of enemies in the dark^ and finding and attacking their weak points.",
            "知能が高く、森に棲む変異種のカラス。\\n不吉な前兆を告げる存在とされ、黒い羽根と赤い目が特徴。\\n闇の中で敵の視界をさえぎり、弱点を見つけて攻撃するのが得意だ。",
            "智力很高、栖息在森林中的变异乌鸦。\\n被视为预示不祥的存在，特征是黑色羽毛与红色眼睛。\\n擅长在黑暗中遮蔽敌人的视线，找出弱点发动攻击。"),
    20003: ("숲의 생명을 지키는 신비로운 존재.\\n초록색 빛을 띠며 나무와 동화된 모습을 하다.\\n이들은 숲의 균형을 유지하고^ 외부 침입자로부터 숲을 보호한다.\\n자연의 힘을 빌려 보호 마법을 사용할 수 있으며^ 숲속 생명체들과 교감한다.",
            "Mysterious beings that protect the life of the forest.\\nThey have a green glow and look like they are one with the trees.\\nThey maintain the balance of the forest^ and protect it from outside invaders.\\nThey can use protective magic by borrowing the power of nature^ and communicate with the creatures of the forest.",
            "森の命を守る神秘的な存在。\\n緑色の光を帯び、木々と一体化した姿をしている。\\n森の均衡を保ち、外からの侵入者から森を守る。\\n自然の力を借りて守りの魔法を使い、森の生き物たちと心を通わせる。",
            "守护森林生命的神秘存在。\\n散发着绿色光芒，模样与树木融为一体。\\n它们维持着森林的平衡，保护森林不受外来入侵者侵扰。\\n能借助自然之力施展守护魔法，并与森林中的生灵心意相通。"),
    20004: ("무리를 지어 다니며^ 민첩성을 지닌 변종 늑대.\\n그들의 털은 숲속에서 뛰어난 위장을 제공하며^ 날카로운 이빨과 발톱으로 무장하고 있다.\\n지능도 높아^ 사냥할 때 전략을 사용하며^ 위험을 감지하면 빠르게 도망치기도 한다.",
            "A mutant wolf that moves in packs and is agile.\\nTheir fur provides excellent camouflage in the forest^ and they are armed with sharp teeth and claws.\\nThey are also highly intelligent^ using strategy when hunting^ and they flee quickly when they sense danger.",
            "群れで行動する、俊敏な変異種の狼。\\nその毛皮は森の中で優れた迷彩となり、鋭い牙と爪で武装している。\\n知能も高く、狩りでは戦略を使い、危険を察するとすばやく逃げることもある。",
            "成群结队、身手敏捷的变异狼。\\n它们的皮毛在森林中是绝佳的伪装，并以锋利的牙齿和爪子武装自己。\\n它们智力也很高，狩猎时会运用战术，察觉危险时也会迅速逃走。"),
    20005: ("거대한 크기와 왕관을 쓴 모습이 특징인 슬라임.\\n여러 종류의 슬라임을 통솔하며^ 그들의 힘을 합쳐 거대한 형태로 변할 수 있다.\\n킹 슬라임의 체내에는 다양한 원소가 섞여 있어^ 공격 시 강력한 화학 반응을 일으킨다.\\n진정한 힘은 평소에는 숨겨져 있지만^ 위기에 처하면 모든 슬라임의 힘을 한데 모아 압도적인 힘을 발휘한다.",
            "A slime characterized by its gigantic size and crowned appearance.\\nIt commands several types of slimes^ and can combine their powers to transform into a gigantic form.\\nKing Slime's body contains a mixture of various elements^ which causes powerful chemical reactions when attacking.\\nIts true power is usually hidden^ but when in danger^ it gathers the power of all the slimes together and displays overwhelming power.",
            "巨大な体と王冠をかぶった姿が特徴のスライム。\\nさまざまなスライムを率い、その力を合わせて巨大な姿に変わることができる。\\nキングスライムの体内には多様な元素が混ざっており、攻撃時に強力な化学反応を起こす。\\n真の力は普段は隠されているが、危機に陥るとすべてのスライムの力を一つに集め、圧倒的な力を発揮する。",
            "以巨大体型和头戴王冠的模样为特征的史莱姆。\\n统领着多种史莱姆，能汇聚它们的力量化为巨大形态。\\n史莱姆王体内混杂着多种元素，攻击时会引发强烈的化学反应。\\n真正的力量平时深藏不露，一旦陷入危机，便会汇聚所有史莱姆的力量，爆发出压倒性的威力。"),
    20006: ("킹 슬라임에 분열되어 둔기 무기를 품은 슬라임.\\n강력한 공격을 하지만 둔해보인다.",
            "A slime split from King Slime and wielding a blunt weapon.\\nIt has powerful attacks but appears dull.",
            "キングスライムから分裂し、鈍器を抱えたスライム。\\n攻撃は強力だが、動きは鈍そうだ。",
            "从史莱姆王分裂而出、怀抱钝器的史莱姆。\\n攻击强力，但看起来有些迟钝。"),
    20007: ("킹 슬라임에 분열되어 단검 무기를 품은 슬라임.\\n재빠른 공격을 하지만 약해보인다.\\n뭔가 반짝이는 게 들어있는 것 같은데?",
            "A slime split from the King Slime and wielding a dagger weapon.\\nIt attacks quickly^ but seems weak.\\nIs there something shiny inside?",
            "キングスライムから分裂し、短剣を抱えたスライム。\\n攻撃はすばやいが、弱そうに見える。\\n何か光るものが入っているような……？",
            "从史莱姆王分裂而出、怀抱短剑的史莱姆。\\n攻击迅速，但看起来很弱。\\n里面好像有什么闪闪发光的东西？"),
    20008: ("킹 슬라임에 분열되어 방패 무기를 품은 슬라임.\\n튼튼한 방어를 하지만 느려보인다.",
            "A slime split from the King Slime and holding a shield weapon.\\nIt has a strong defense^ but appears slow.",
            "キングスライムから分裂し、盾を抱えたスライム。\\n守りは堅いが、動きは遅そうだ。",
            "从史莱姆王分裂而出、怀抱盾牌的史莱姆。\\n防御坚固，但看起来行动迟缓。"),
}
