"""UI translations and the small, generated fallback needed before Addressables loads."""
import json
from pathlib import Path

# Korean, English, Japanese, Simplified Chinese. IDs are shared with Define.cs.
TEXT = {
    133: ("예상 피해", "Expected damage", "予想ダメージ", "预计伤害"),
    134: ("쓰러진다", "You will fall", "倒れます", "将会倒下"),
    135: ("못 이긴다", "Cannot win", "勝てません", "无法获胜"),
    140: ("게임 시작", "Start game", "ゲーム開始", "开始游戏"),
    141: ("새 게임", "New game", "ニューゲーム", "新游戏"),
    142: ("이어하기", "Continue", "つづきから", "继续游戏"),
    143: ("아무 키나 누르세요", "Press any key", "何かキーを押してください", "请按任意键"),
    144: ("불러오지 못했습니다. Enter: 재시도 / Esc: 종료", "Loading failed. Enter: retry / Esc: quit",
          "読み込めませんでした。Enter：再試行 / Esc：終了", "加载失败。Enter：重试 / Esc：退出"),
    145: ("저장을 복구하지 못했습니다. 원본은 보존됩니다. 아무 키나 눌러 돌아가세요.",
          "Could not restore your save. The original is preserved. Press any key to return.",
          "セーブを復元できませんでした。元のデータは保持されます。何かキーを押して戻ります。",
          "无法恢复存档。原始存档已保留。请按任意键返回。"),
    146: ("둘 중 하나를 얻으면 다른 보상은 사라집니다.", "Taking one reward removes the other.",
          "片方を取ると、もう片方の報酬は消えます。", "领取一个奖励后，另一个奖励将消失。"),
    147: ("지금 마시면 {0} 이 넘쳐 사라집니다.", "Drinking now wastes {0} HP.",
          "今飲むと {0} が溢れて失われます。", "现在饮用将溢出 {0} 点生命。"),
}


def append_rows(scripts):
    by_id = {row["id"]: row for row in scripts}
    for sid, values in TEXT.items():
        row = dict(id=sid, **dict(zip(("ScriptKr", "ScriptEn", "ScriptJp", "ScriptCn"), values)))
        if sid in by_id:
            by_id[sid].update(row)
        else:
            scripts.append(row)


def emit_bootstrap(root):
    path = Path(root) / "Assets/@Scripts/Data/GeneratedUiText.cs"
    lines = ["// Generated by Tools/ui_text.py through generate_content.py. Do not edit.",
             "public static class GeneratedUiText", "{", "    public static string Get(int id, int language)",
             "    {", "        switch (id)", "        {"]
    for sid, (kr, en, jp, cn) in TEXT.items():
        values = ", ".join(json.dumps(v, ensure_ascii=False) for v in (en, kr, en, jp, cn))
        lines.append(f"            case {sid}: return new[] {{ {values} }}[language >= 0 && language <= 4 ? language : 0];")
    lines += ["            default: return null;", "        }", "    }", "}"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
